### ISSUE TITLE
Add NRW.mobil Provider

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#21]
Uses the HCI interface with mic/mac.

**Comment by derhuerst** [comment]
FYI the endpoint doesn't require `mic`/`mac` to be passed.

**Comment by alexander-albers** [comment]
> FYI the endpoint doesn't require `mic`/`mac` to be passed. [working but WIP `hafas-client` implementation](https://github.com/public-transport/hafas-client/blob/ddde8ffb20ede04c3cbb6e84378e0b45b373771e/p/mobil-nrw/index.js)

Good to know, thanks!
