### ISSUE TITLE
Make max walk time configurable

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#24]
Efa: https://github.com/alexander-albers/tripkit/blob/e8d7236141f3ff1b1dc74cbb9f1fac06c6a5db31/Sources/TripKit/AbstractEfaProvider.swift#L1547
Hafas: https://github.com/alexander-albers/tripkit/blob/e8d7236141f3ff1b1dc74cbb9f1fac06c6a5db31/Sources/TripKit/AbstractHafasClientInterfaceProvider.swift#L919 (is there another parameter for time?)

**Comment by derhuerst** [comment]
related: https://github.com/public-transport/hafas-client/issues/218

These are all that I could find related to walking/cycling/intermodality. If you find more, please let me know!

**Comment by alexander-albers** [comment]
I couldn't find any parameter for max footpath time in hafas, unfortunately, so I added both the max distance and max time TripOption.
