### ISSUE TITLE
Hci: Support more journey types

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#27]
There are still journey types which are not being parsed in AbstractHciProvider and result in a parse error:

- BIKE: Bike
- KISS: Car
- PARK: Park & Ride
- TAXI: Taxi
- CHKI: Check-In
- CHKO: Check-Out

I haven't encountered any of the above mentioned types in the wild, except for one case: BVG requires that the product type "BERLKOENIG" is included, or otherwise some trips may fail, even if those don't include any Berlkönig products (see #26).

**Comment by derhuerst** [comment]
I think HAFAS responds with `BIKE`, `KISS`, `PARK` & `TAXI` if you request multimodal and intermodal journeys (see also https://github.com/public-transport/hafas-client/issues/218).
