### ISSUE TITLE
BVG doesn't work

### ISSUE THREAD

**Issue by johannesweise** [alexander-albers/tripkit#48]
Cannot get any connections with BVG.
Other providers work, but BVG doesn't.

**Comment by alexander-albers** [comment]
The endpoint that my app accesses is down unfortunately: https://bvg.hafas.cloud. The BVG app and website automatically fall back to an older endpoint, but unfortunately this functionality is not implemented here. I expect the service to resume in the next hours again.

**Comment by derhuerst** [comment]
related: https://github.com/schildbach/public-transport-enabler/issues/418

**Comment by derhuerst** [comment]
> The BVG app and website automatically fall back to an older endpoint [...].

How does it work? Using `mitmproxy` and the Firefox devtools, I couldn't confirm that. 🤔

Both call `bvg-apps.hafas.de` which redirects temporarily (`307`) to `bvg-apps-ext.hafas.de`.

**Comment by alexander-albers** [comment]
Hm I thought I have seen direct calls to bvg.hafas.cloud in the past, but maybe I've confused something. You're definitely right, the BVG apps call bvg-apps.hafas.de and then get redirected automatically to the second endpoint. It would probably make sense to employ the same strategy here, i.e. revert back to calling bvg-apps.hafas.de.
