### ISSUE TITLE
HCI: parse more messages and remark texts

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#56]
Avv Aachen: operator and "behindertengerecht"

Rmv, Nvv: "3g", "geringe Belegung"

Gvh: "behindertengerechtes Fahrzeug"

~In general, deduplication of messages does not seem to work.~

**Comment by alexander-albers** [comment]
> FYI: I keep a list of those that I stumble upon here: [public-transport/hafas-client#5](https://github.com/public-transport/hafas-client/issues/5)

Yeah, I've seen your list - really great job. My goal for TripKit is to parse only some relevant messages (like wheelchair access, bicycle carriage or the load factor), filter out redundant information (like the line operator or line number) and default to displaying everything else. I think parsing everything would be way too hard and you still could not guarantee a fully complete list as new types are being added all the time.

**Comment by derhuerst** [comment]
In case you find out what the different codes mean, just reply over there. 🙌 This way, we can join our forces/efforts.
