### ISSUE TITLE
Add Tirol provider

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#60]

**Comment by derhuerst** [comment]
FYI You could pull the current API details from [`transport-apis`](https://github.com/public-transport/transport-apis), like `kpublictransport` & `hafas-client` do it. This way, the work of investigating changing endpoints or access tokens will ideally only have to be done once.

**Comment by derhuerst** [comment]
> @I'm considering integrating the repo in the medium term, however for the current time being this would just mean a lot of work for a minor convenience imo.

Yeah, `transport-apis` is definitely not worth it short-term, the idea is to make long-term maintenance less cumbersome.

> the limiting factor is creating [...] geojson coverage files, creating all line styles and collecting a list of all route map pdfs.

[GeoJSON coverage is already part of the `transport-apis` schema](https://github.com/public-transport/transport-apis/blob/4257051281665e266bd33b2da1d03c9615c57a8f/readme.md#coverage-information) (maybe not with the same semantics as `TripKit`'s).

Let's discuss integrating line stiles and possibly even route maps into `transport-apis` as well, if you have time!
