### ISSUE TITLE
Latest Swift Package 1.15.4 does not compile because of Hvv GeoFox Crypto 

### ISSUE THREAD

**Issue by GerdC** [alexander-albers/tripkit#66]
I'm adding latest TripKit with Swift Package Manager which results in TripKit 1.15.4

Compiling fails in `HvvProvider`:

```
    var hash = [UInt8](repeating: 0, count: Int(CC_SHA1_DIGEST_LENGTH))
                    CCHmac(CCHmacAlgorithm(kCCHmacAlgSHA1), keyBytes.baseAddress, key.count, bytes.baseAddress, data.count, &hash)
                    return hash
```

Identifiers `CC_SHA1_DIGEST_LENGTH`, `CCHmac`, `CCHmacAlgorithm`, and `kCCHmacAlgSHA1` are not defined.

**Comment by alexander-albers** [comment]
Thanks for the tip, I wonder why this ever compiled in the first place. Could you please check again using the master branch?

**Comment by GerdC** [comment]
Yes, referencing the main (not master) branch works

**Comment by alexander-albers** [comment]
Ah right, I mean main of course. Good to hear 👍
