### ISSUE TITLE
Swift Package Manager:  "found 4 file(s) which are unhandled; explicitly declare them as resources or exclude from the target"

### ISSUE THREAD

**Issue by GerdC** [alexander-albers/tripkit#67]
Importing TripKit via Swift Package Manager gives 4 warnings:
found 4 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
The files are info*.plist

These are only warnings, but it would be nice if they were handled explicitly.

**Comment by alexander-albers** [comment]
Fixed with https://github.com/alexander-albers/tripkit/commit/280c55d440b2b4d6093176709b422b8395cef414.
