### ISSUE TITLE
HCI: test supported API versions

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#69]
I would like to figure out at some point which Hafas API versions are actually supported by the current TripKit implementation. Ideally, I would then like to bump all provider implementations to at least the same version that the official websites or apps are using.

One benefit of newer Hafas versions is more detailed error messages, but I'm sure there are a lot more improvements in other areas as well.

**Comment by derhuerst** [comment]
> I would like to figure out at some point which Hafas API versions are actually supported by the current TripKit implementation. Ideally, I would then like to bump all provider implementations to at least the same version that the official websites or apps are using.

For `hafas-client`], I have written [a tool that tries to find the highest reported-to-be-supported HCI version](https://github.com/public-transport/hafas-client/blob/4b8f7c81981832c31ddd3a820864aef706c47168/tools/highest-endpoint-version/cli.js#L33-L78) for an endpoint.

Its detection logic seems to be a bit brittle though, probably not all endpoints/versions actually support versions that they *don't* throw an error for. Please let me know if you find a more reliable way.

> One benefit of newer Hafas versions is more detailed error messages, but I'm sure there are a lot more improvements in other areas as well.

Yes, there are many others; Most of the features mentioned in https://github.com/public-transport/hafas-client/issues/3 got introduced by a bumped version.

**Comment by alexander-albers** [comment]
@derhuerst Thanks a lot for your insights!

> For hafas-client], I have written a tool that tries to find the highest reported-to-be-supported HCI version for an endpoint.

My first idea was to merely look what versions the official apps use, but your method seems a lot better. I would still of course need to test whether the detected version is really supported by the server, but I would have to do this nevertheless to see if the client-side implementation of TripKit works with the changed version.

> Most of the features mentioned in public-transport/hafas-client#3 got introduced by a bumped version.

Good to know. But since I also ideally want to support every feature for Efa providers as well, this means that I still have to go for the lowest common denominator.

**Comment by derhuerst** [comment]
> But since I also ideally want to support every feature for Efa providers as well, this means that I still have to go for the lowest common denominator.

Sure, on the "outside" of `TripKit`, you won't be able to expose all those feature. But you can at least use the latest HCI versions on the inside, to benefit e.g. from better error messages.

**Comment by alexander-albers** [comment]
Here's a list of all backend api versions:

| Provider | API-Version |
| ---      | ---       |
| DB | 1.46 |
| BVG | 1.45 |
| VBB | 1.45 |
| RMV | 1.50 |
| AVV (Aachen) | 1.51 |
| INVG | 1.52 |
| NVV | 1.50 |
| SH | 1.44 |
| GVH | 1.53 |
| VBN | 1.52 |
| NASA | 1.48 |
| VSN | 1.52 |
| VOS | 1.52 |
| VMT | 1.54 |
| NRW | 1.46 |
| VGS | 1.54 |
| ZVV | 1.54 |
| OEBB | 1.54 |
| VOR | 1.52 |
| OOEVV | 1.52 |
| IVB | 1.52 |
| SVV | 1.52 |
| VVT | 1.52 |
| STV | 1.52 |
| VMOBIL | 1.52 |

**Comment by alexander-albers** [comment]
@derhuerst it seems like the easiest way to get the latest server version is to make a request with a too high version number (like 1.99). The server will then respond with the currently running version in its error response.

https://github.com/alexander-albers/tripkit/blob/19b5d092446303a30b109f71412e359466ace180/Tests/TripKitTests/HCIVersionChecker.swift#L47

Response:
```json
{
  "ver": "1.46",
  "err": "VERSION",
  "errTxt": "Invalid version: 1.99"
}
```

However, GVH and NASA return a http error status code, meaning that for those two providers your script is still the best solution.

**Comment by derhuerst** [comment]
> it seems like the easiest way to get the latest server version is to make a request with a too high version number (like 1.99). The server will then respond with the currently running version in its error response.

True, that's much more efficient. I also discovered that you can use the `ServerInfo` call:

```json
{"lang":"de","svcReqL":[{"meth":"ServerInfo","req":{}}],"client":{"type":"WEB","id":"VAO","name":"webapp"},"ext":"VAO.11","ver":"1.39","auth":{"type":"AID","aid":"wf7mcf9bv3nv8g5f"}}
```

```json
{"ver":"1.39","ext":"VAO.11","lang":"deu","id":"naiiskmxg6ws9m8x","err":"OK","cInfo":{"code":"OK","url":"","msg":""},"graph":{"id":"standard","index":0},"subGraph":{"id":"global","index":0},"view":{"id":"standard","index":0,"type":"WGS84"},"svcResL":[{"meth":"ServerInfo","err":"OK","res":{"fpB":"20211216","fpE":"20221210","sD":"20220217","sT":"021501","enc":"UTF-8","planrtTS":"1645060476"}}]}
```

**Comment by alexander-albers** [comment]
Ahh right, I had something like this in my mind as well but forgot how the method was called. Thanks!

**Comment by alexander-albers** [comment]
However, it seems like the version returned from `ServerInfo` still matches the one in the request. So you still wouldn't be able to find out the latest version using this.

**Comment by alexander-albers** [comment]
I found out how to reliably get the current hci version:

<details>
<summary>Request</summary>

```json
{
  "svcReqL": [
    {
      "req": {
        "getVersionInfo": true
      },
      "meth": "ServerInfo"
    }
  ],
  "ext": "DB.R21.12.a",
  "formatted": true,
  "auth": {
    "type": "AID",
    "aid": ""
  },
  "client": {
    "type": "IPH",
    "name": "DB Navigator",
    "v": "20100000",
    "id": "DB"
  },
  "ver": "1.40",
  "lang": "de"
}
```
</details>


<details>
<summary>Response</summary>


```json
{
  "ver": "1.45",
  "ext": "DB.R21.12.a",
  "lang": "deu",
  "id": "",
  "err": "OK",
  "cInfo": {
    "code": "OK",
    "url": "",
    "msg": ""
  },
  "svcResL": [
    {
      "meth": "ServerInfo",
      "err": "OK",
      "res": {
        "fpB": "20211212",
        "fpE": "20221210",
        "sD": "20220222",
        "sT": "194520",
        "enc": "ISO-8859-1",
        "planrtTS": "1645555430",
        "serverVersion": "5.45.DB.R21.12.1.a (customer/hcudb/release/21.12.1.a.0) [Dec 17 2021]",
        "clientVersion": "5.45.DB.R21.12.1.a (customer/hcudb/release/21.12.1.a.0) [Dec 17 2021]",
        "hciVersion": "1.46"
      }
    }
  ]
}
```
</details>
