### ISSUE TITLE
Support different languages

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#70]
Many transit providers have translations for stop names or info texts, at least for English language. TripKit should ideally have an option to supply a language code to the requests (or a variable of the provider), similar to how [hafas-client](https://github.com/public-transport/hafas-client/blob/4b8f7c81981832c31ddd3a820864aef706c47168/lib/request.js#L77) does it.

This parameter could default to the current locale and check in a mapping of supported language codes whether this language can be used or whether English/the provider default language should be used.

For Hafas Legacy, [this page](https://administrator.de/knowledge/hafas-fahrplanauskunft-api-sammlung-177145.html#:~:text=Sprachcodes%20in%20den%20URLs) gives a good overview of supported codes and their meaning.
For Efa, the `language` request url parameter can take any ISO 638:1988 value.

**Comment by derhuerst** [comment]
> For Hafas, [this page](https://administrator.de/knowledge/hafas-fahrplanauskunft-api-sammlung-177145.html#:~:text=Sprachcodes%20in%20den%20URLs) gives a good overview of supported codes and their meaning. 

This page is about the web-based HAFAS APIs, not about the `mgate.exe` flavour. The latter works differently, and also it used to work inconsistently from endpoint to endpoint (e.g. `de` vs `deu`). [`public-transport/transport-apis` aims to provide an up-to-date list of supported languages](https://github.com/public-transport/transport-apis/search?q=supportedLanguages), so if you see something outdated, please report it.
