### ISSUE TITLE
README.md: examples use IDs that don't exist

### ISSUE THREAD

**Issue by GerdC** [alexander-albers/tripkit#73]
Using the example from `README.md`

    provider.queryTrips(from: Location(id: "7000001"), via: nil, to: Location(id: "7000002"))

returns error messages that suggest that id's "7000001" and "7000002" don't exist in Karlsruhe (any more).
(I replaced the IDs with coordinates, then it worked.)

This is not a bug in the library, but fixing this would make it easier for newbies to avoid frustration.

**Comment by alexander-albers** [comment]
Thanks, that's probably because they opened a new subway station there. Our Kombilösung has beaten your Stuttgart 21, in terms of its launch date ;)

I'll update the readme soon.
