### ISSUE TITLE
Can't add Api Keys

### ISSUE THREAD

**Issue by victorlobe** [alexander-albers/tripkit#78]
Its not possible to add Api keys for DB anywhere.

**Comment by alexander-albers** [comment]
You can initialize the DB provider as follows:

```swift
let provider = DbProvider(
      apiAuthorization: [
            "type": "AID",
            "aid": ""
      ],
      requestVerification: AbstractHafasClientInterfaceProvider.RequestVerification.checksum(salt: "")
)
```

You can find the required struct format for the respective provider here: https://github.com/alexander-albers/tripkit/blob/main/Sources/TripKit/Resources/secrets.json.template
For running the tests, you need to copy secrets.json.template to secrets.json and fill out the necessary keys.

**Comment by victorlobe** [comment]
Thank you very much for your quick response. I got a „client Id“ and a „client secret (api key)“, I pasted the secret key to the aid line but I don’t work. 
which keys do I have to add at which line?

**Comment by alexander-albers** [comment]
I'm not sure if we are talking about the same API. What endpoint are you trying to reach?

**Comment by victorlobe** [comment]
I am trying to reach the DB API, I got the following data: 

![Uploading 4DE7502B-4BB5-4D2C-892C-9922F729BF99.jpeg…]()

**Comment by alexander-albers** [comment]
Unfortunately, this API is not supported by TripKit. You need to obtain a different key similar to the one the official DB Navigator app uses.

**Comment by victorlobe** [comment]
Ah ok, now I understand. Thank you very much! And keep up the good work :)
