### ISSUE TITLE
HVV Provider return Stops but no other data

### ISSUE THREAD

**Issue by victorlobe** [alexander-albers/tripkit#82]
The HVV Provider can’t fetch data for every request except search stations. The navigator app also has the same bug.

**Comment by alexander-albers** [comment]
I couldn't reproduce this issue. Could you please attach an error log? You can generate one from the ÖPNV Navigator in the More tab under "About".

**Comment by victorlobe** [comment]
I generated the error log [Here](https://mega.nz/file/UxJz3IBC#lLjzG8BZ3aNk31EEAsXEMR1x2HIMVwz8rRDQi-qs-EU) 

I tried it again a couple times and the stations in Hamburg seem to work but all smaller stations outside of Hamburg return an empt result in my example it is the station „Ratzeburg Vorstadtschule“

**Comment by alexander-albers** [comment]
Thank you. This seems to be an issue with their API. Changing the request url to https://www.hvv.de/geofox/departureList with the same request works without any issues. I have contacted their support.

**Comment by victorlobe** [comment]
Thanks! Should I close the issue or wait until they have responded?

**Comment by alexander-albers** [comment]
Keep it open. I will keep you posted when they respond.

**Comment by victorlobe** [comment]
Perfect, thank you!

**Comment by alexander-albers** [comment]
Got a reply from the API provider saying that they reproduced the issue and have opened an internal ticket.

**Comment by victorlobe** [comment]
Perfect! Then I close the issue. Thanks!

**Comment by alexander-albers** [comment]
The HVV provider should now also return departures for the RMVB provider (Ratzeburg und Möllner Verkehrsbetriebe).

**Comment by victorlobe** [comment]
Perfect, Thanks!
