### ISSUE TITLE
HVV Provider Return Stations and trips but no departures or trip details.

### ISSUE THREAD

**Issue by victorlobe** [alexander-albers/tripkit#86]
Edit: in the navigator app, everything works fine but the bug is in the tripKit Api.

**Comment by alexander-albers** [comment]
> Edit: in the navigator app, everything works fine but the bug is in the tripKit Api.

That seems odd to me. Could you please give an example and also attach the diagnostics file from ÖPNV Navigator under More → About? You can also send me the file privately on navigatorapp.net/help.
