### ISSUE TITLE
AbstractEfaWebProvider queryJourneyDetail seems not to work for Bvb

### ISSUE THREAD

**Issue by cseh17** [alexander-albers/tripkit#87]
queryJourneyDetail in the AbstractEfaWebProvider for BvB (Basel) always delivers an invalidId as a response. 
From what I was able to check, this might happen due to a missing suffix for the lineId that is provided in the QueryJourneyDetailContext that is used for the request. 
(lucky guess, but maybe ":1") - checked on the Bvb website. 

Could you please check this?

**Comment by alexander-albers** [comment]
Could you please provide an example? I did not have any problems in the TripKit test case:

Departures:
> https://www.efa-bw.de/bvb3/XSLT_DM_REQUEST?outputFormat=XML&language=en&stateless=1&coordOutputFormat=WGS84&type_dm=stop&name_dm=51000095&itdDate=20230726&itdTime=0945&useRealtime=1&mode=direct&ptOptionsActive=1&deleteAssignedStops_dm=1&useProxFootSearch=0&mergeDep=1&limit=5&itdDateTimeDepArr=dep

Journey detail:
> https://www.efa-bw.de/bvb3/XML_STOPSEQCOORD_REQUEST?outputFormat=XML&language=en&stateless=1&coordOutputFormat=WGS84&stopID=51000095&tripCode=44&line=bvb:01003:%20:R:n23&date=20230726&time=0948&tStOTType=all

**Comment by cseh17** [comment]
Thanks for the feedback! As it seems, the stationId is wrong in my request. Where do you get yours from? It seems that is not from GTFS.

**Comment by alexander-albers** [comment]
You can use [NetworkProvider.suggestLocations](https://github.com/alexander-albers/tripkit/blob/7bd0638f83faab1fb1de89537ecd80cd1f4a029f/Sources/TripKit/Provider/NetworkProvider.swift#L39) to query the stationId for your desired station name. Why the ids from GTFS aren't compatible is an entirely different topic and a pet peeve of mine. Unfortunately, there isn't much that we can do.

**Comment by cseh17** [comment]
Yep, this works. Thank you a lot! This was a big help. And sorry for the confusion, it was not an issue at all.
