### ISSUE TITLE
Add VRT (Trier) network provider

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#9]

**Comment by alexander-albers** [comment]
Endpoint base url: https://www.vrt-info.de/fahrplanauskunft/XSLT_TRIP_REQUEST2

**Comment by derhuerst** [comment]
See also schildbach/public-transport-enabler#182.

**Comment by alexander-albers** [comment]
> See also [schildbach/public-transport-enabler#182](https://github.com/schildbach/public-transport-enabler/issues/182).

Thanks for the note. It‘s a little confusing that their efa api is still being used on their website, but if the VRN provides the same data there is no reason to include the VRT here.

I‘ll keep this issue opened until I‘ve added all line styles for Trier in the VRN Provider.
