### ISSUE TITLE
HVV Netzpläne (USAR) nicht verfügbar

### ISSUE THREAD

**Issue by ParoTheParrot** [alexander-albers/tripkit#91]
mit dem Fahrplanwechsel gibt es neue Netzpläne, siehe https://www.hvv.de/de/plaene.
Die alten sind  nicht mehr verfügbar (Fehlermeldung)

**Comment by alexander-albers** [comment]
Hallo, danke für den Hinweis. Das Problem hängt mit dem ÖPNV Navigator zusammen, nicht mit der Library hier. Ich aktualisiere die Netzpläne immer jährlich per Hand, meist zwischen den Jahren.

**Comment by ParoTheParrot** [comment]
Kann ich bei der Aktualisierung der Pläne irgendwie unterstützen?
Ich habe die jetzt bei hvv.de heruntergeladen und separat abgelegt  - unschön.
[Uploading hvv_usar-plan_2023-12-04.pdf…]()

**Comment by alexander-albers** [comment]
Netzpläne sind jetzt aktualisiert

**Comment by ParoTheParrot** [comment]
> Netzpläne sind jetzt aktualisiert

Danke. Knapp drei Monate verspätet, aber immerhin. 
Wie bereits angeboten biete ich meine Hilfe an - für kommendes Jahr.
