### ISSUE TITLE
Add NeTEx support

### ISSUE THREAD

**Issue by Robot8A** [alexander-albers/tripkit#92]
By supporting NeTEx, a large chunk of Italy could be added (and, in the future, all of it) to ÖPNV Navigator (see: https://github.com/public-transport/transitous/issues/117). The Italian government is now working on publishing every region's public transport as NeTEx, not GTFS, to their [NAP](https://nap-1926.it/nap/mmtis/public/catalog/Dataset).

**Comment by alexander-albers** [comment]
As far as I can tell, NeTEx only provides planned timetable data (similar to GTFS). TripKit cannot calculate routes by itself and relies on a third-party service to do so.
