### ISSUE TITLE
Add Norway to ÖPNV Coverage

### ISSUE THREAD

**Issue by Robot8A** [alexander-albers/tripkit#93]
GTFS / NeTEx:
https://developer.entur.org/stops-and-timetable-data

GTFS-RT / SIRI:
https://developer.entur.org/pages-real-time-intro

**Comment by alexander-albers** [comment]
As mentioned in issue #92, TripKit does not work with GTFS files.

Furthermore, please refrain from creating issues to support a particular transit network in the future. If you want it to be added, I am happy to consider your Pull Request.

**Comment by Robot8A** [comment]
Norway has a national routing service, so it could still be considered:
https://developer.entur.org/pages-journeyplanner-journeyplanner
I do not know how difficult it would be to implement.

**Comment by alexander-albers** [comment]
Open Trip Planner and Open Journey Planner are both services that would be nice to support in the future. However, at the moment, I do not have the time to work on it by myself and would need someone who not only would be interested in implementing it but also in maintaining it over the long run.
