### ISSUE TITLE
Problem with fetching data from BVG/VBB or DB

### ISSUE THREAD

**Issue by ankraft** [alexander-albers/tripkit#99]
Since an about a week now the "ÖPNV Navigator" apps (IoS and MacOS) seem to problems to fetch data from the above local service providers. The error message is "Could not fetch trips - Illegal response: the response of the network provider could not be parsed."

**Comment by hejjoe** [comment]
@ankraft This issue should be fixed with app version 1.21.3, which was released today. https://apps.apple.com/de/app/%C3%B6pnv-navigator/id1239908782 
![grafik](https://github.com/user-attachments/assets/c6308bff-55ba-4b51-a62d-87d7215f6907)

**Comment by alexander-albers** [comment]
Yup, thanks

**Comment by ankraft** [comment]
Thanks!
